package com.qring.print;

import android.app.*;
import android.bluetooth.*;
import android.content.*;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.util.*;

public class DevicePickerActivity extends Activity {
    private final LinkedHashMap<String,BluetoothDevice> devices=new LinkedHashMap<>();private LinearLayout list;private TextView state;private ProgressBar scanning;private BluetoothAdapter adapter;private boolean registered;
    private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){String a=i.getAction();if(BluetoothDevice.ACTION_FOUND.equals(a)){BluetoothDevice d=Compat.parcelableExtra(i,BluetoothDevice.EXTRA_DEVICE,BluetoothDevice.class);if(d!=null){add(d);render();}}else if(BluetoothAdapter.ACTION_DISCOVERY_STARTED.equals(a)){state.setText("正在扫描附近设备…");scanning.setVisibility(View.VISIBLE);}else if(BluetoothAdapter.ACTION_DISCOVERY_FINISHED.equals(a)){state.setText("扫描完成 · 选择设备即可配对/连接");scanning.setVisibility(View.GONE);}else if(BluetoothDevice.ACTION_BOND_STATE_CHANGED.equals(a)){BluetoothDevice d=Compat.parcelableExtra(i,BluetoothDevice.EXTRA_DEVICE,BluetoothDevice.class);if(d!=null){add(d);render();try{if(d.getBondState()==BluetoothDevice.BOND_BONDED)connect(d);}catch(Throwable ignored){}}}}};
    @Override public void onCreate(Bundle b){super.onCreate(b);BluetoothManager bm=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);adapter=bm!=null?bm.getAdapter():BluetoothAdapter.getDefaultAdapter();setContentView(build());if(!Compat.hasBluetoothPermissions(this))Compat.requestBluetoothPermissions(this);}
    @Override protected void onStart(){super.onStart();registerBt();loadBonded();}
    @Override protected void onStop(){stopScan();unregisterBt();super.onStop();}
    private View build(){ScrollView sc=new ScrollView(this);LinearLayout root=Ui.page(this,"连接打印机");sc.addView(root);
        LinearLayout hero=Ui.card(this);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);TextView mark=Ui.pill(this,"BT",Ui.PRIMARY);row.addView(mark);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView t=new TextView(this);t.setText("寻找 Qring / BeePrt 打印机");t.setTextSize(18);t.setTextColor(Ui.TEXT);t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);state=Ui.hint(this,"已配对设备会优先显示；也可以扫描附近设备。 ");tx.addView(t);tx.addView(state);row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));scanning=new ProgressBar(this);scanning.setIndeterminate(true);scanning.setVisibility(View.GONE);row.addView(scanning,new LinearLayout.LayoutParams(Ui.dp(this,32),Ui.dp(this,32)));hero.addView(row);Button scan=Ui.primaryButton(this,"扫描附近设备");scan.setOnClickListener(v->scan());hero.addView(scan);Button settings=Ui.button(this,"打开系统蓝牙设置");settings.setOnClickListener(v->{try{startActivity(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS));}catch(Throwable e){Ui.toast(this,"无法打开设置");}});hero.addView(settings);root.addView(hero);
        root.addView(Ui.section(this,"附近与已配对设备","名称匹配 Qring / BeePrt / BY 的设备会排在前面。"));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);return sc;}
    private void registerBt(){if(registered)return;IntentFilter f=new IntentFilter();f.addAction(BluetoothDevice.ACTION_FOUND);f.addAction(BluetoothAdapter.ACTION_DISCOVERY_STARTED);f.addAction(BluetoothAdapter.ACTION_DISCOVERY_FINISHED);f.addAction(BluetoothDevice.ACTION_BOND_STATE_CHANGED);try{Compat.registerBluetoothReceiver(this,receiver,f);registered=true;}catch(Throwable e){state.setText("蓝牙监听启动失败："+e.getMessage());}}
    private void unregisterBt(){if(!registered)return;try{unregisterReceiver(receiver);}catch(Throwable ignored){}registered=false;}
    private void loadBonded(){devices.clear();for(BluetoothDevice d:PrinterManager.get(this).bonded(this))add(d);render();}
    private void add(BluetoothDevice d){try{devices.put(d.getAddress(),d);}catch(Throwable ignored){}}
    private void scan(){if(adapter==null){Ui.toast(this,"设备没有蓝牙硬件");return;}if(!Compat.hasBluetoothPermissions(this)){Compat.requestBluetoothPermissions(this);return;}try{if(!adapter.isEnabled()){Ui.toast(this,"请先打开蓝牙");return;}if(adapter.isDiscovering())adapter.cancelDiscovery();boolean ok=adapter.startDiscovery();if(!ok){state.setText("系统未启动扫描，请检查蓝牙/位置服务和权限");scanning.setVisibility(View.GONE);}}catch(Throwable e){state.setText("扫描失败："+e.getMessage());scanning.setVisibility(View.GONE);}}
    private void stopScan(){try{if(adapter!=null&&adapter.isDiscovering())adapter.cancelDiscovery();}catch(Throwable ignored){}}
    private void render(){list.removeAllViews();ArrayList<BluetoothDevice> a=new ArrayList<>(devices.values());Collections.sort(a,(x,y)->{boolean xm=PrinterManager.matchesPrinterName(PrinterManager.safeName(x)),ym=PrinterManager.matchesPrinterName(PrinterManager.safeName(y));if(xm!=ym)return xm?-1:1;return PrinterManager.safeName(x).compareToIgnoreCase(PrinterManager.safeName(y));});if(a.isEmpty()){list.addView(Ui.emptyState(this,"BT","暂未发现打印机","让打印机开机并靠近手机。已配对设备会立即出现，附近新设备可通过经典蓝牙扫描发现。","重新扫描",v->scan()));return;}for(BluetoothDevice d:a){int bond;String addr="";try{bond=d.getBondState();addr=d.getAddress();}catch(Throwable e){bond=BluetoothDevice.BOND_NONE;}boolean recommended=PrinterManager.matchesPrinterName(PrinterManager.safeName(d));LinearLayout card=Ui.card(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);TextView icon=Ui.pill(this,recommended?"✓":"BT",recommended?Ui.SUCCESS:Ui.PRIMARY);r.addView(icon);LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);TextView n=new TextView(this);n.setText(PrinterManager.safeName(d));n.setTextSize(17);n.setTextColor(Ui.TEXT);n.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);copy.addView(n);TextView m=Ui.hint(this,addr+(recommended?" · 推荐设备":""));m.setPadding(0,0,0,0);copy.addView(m);r.addView(copy,new LinearLayout.LayoutParams(0,-2,1));TextView badge=Ui.pill(this,bond==BluetoothDevice.BOND_BONDED?"已配对":"需配对",bond==BluetoothDevice.BOND_BONDED?Ui.SUCCESS:Ui.WARNING);r.addView(badge);card.addView(r);card.setOnClickListener(v->select(d));Ui.pressMotion(card);list.addView(card);}}
    private void select(BluetoothDevice d){stopScan();try{if(d.getBondState()!=BluetoothDevice.BOND_BONDED){state.setText("正在请求系统配对…");if(!d.createBond())Ui.toast(this,"无法启动配对，请在系统蓝牙设置中配对");}else connect(d);}catch(Throwable e){Ui.toast(this,"配对失败："+e.getMessage());}}
    private void connect(BluetoothDevice d){state.setText("正在连接 "+PrinterManager.safeName(d)+"…");scanning.setVisibility(View.VISIBLE);PrinterManager.get(this).connect(this,d,(ok,msg)->{scanning.setVisibility(View.GONE);Ui.toast(this,msg);if(ok){setResult(RESULT_OK);finish();}else state.setText(msg);});}
}
