package com.qring.print;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.os.Bundle;
import android.provider.MediaStore;
import android.text.*;
import android.view.View;
import android.widget.*;
import com.google.zxing.Result;
import java.util.*;

public class ProductDatabaseActivity extends Activity {
    private static final int PICK_TABLE=1101,PICK_CODE=1102,CAMERA=1103;
    private DataTableReader.Table table;private Spinner keyColumn;private EditText query,template;private TextView info,match;private ImageView preview;private int matched=-1;private Bitmap rendered,previewBitmap;
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(build());if(ProductStore.exists(this))try{setTable(ProductStore.load(this),"已载入本地商品库");}catch(Throwable ignored){}}
    private View build(){
        ScrollView sc=new ScrollView(this);LinearLayout root=Ui.page(this,"商品信息库");sc.addView(root);
        LinearLayout db=Ui.card(this);db.addView(Ui.hint(this,"CSV / XLSX 本地商品库 · 扫码查商品 · 自定义字段模板。数据只保存在本机。"));Button imp=Ui.primaryButton(this,"导入 / 更新商品库");imp.setOnClickListener(v->pickTable());db.addView(imp);info=Ui.hint(this,"尚未导入商品数据");db.addView(info);keyColumn=new Spinner(this);db.addView(keyColumn);query=new EditText(this);query.setHint("输入商品条码 / 编号 / 关键字");db.addView(query);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button find=Ui.button(this,"查找"),scan=Ui.button(this,"扫码图片"),cam=Ui.button(this,"拍照扫码");find.setOnClickListener(v->find(query.getText().toString().trim()));scan.setOnClickListener(v->pickCode());cam.setOnClickListener(v->camera());row.addView(find,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));row.addView(scan,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));row.addView(cam,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));db.addView(row);root.addView(db);
        match=Ui.hint(this,"未选择商品");root.addView(match);
        LinearLayout tpl=Ui.card(this);tpl.addView(Ui.hint(this,"标签模板 · 使用 {字段名} 自动替换商品数据"));template=new EditText(this);template.setHint("例如：\n{name}\n¥{price}\n{barcode}");template.setMinLines(5);tpl.addView(template,new LinearLayout.LayoutParams(-1,Ui.dp(this,150)));root.addView(tpl);
        preview=new ZoomablePreviewView(this);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);preview.setBackgroundColor(Color.WHITE);root.addView(Ui.previewFrame(this,preview,"当前商品标签预览"),new LinearLayout.LayoutParams(-1,Ui.dp(this,280)));
        Button print=Ui.primaryButton(this,"预览确认并打印当前商品");print.setOnClickListener(v->printMatched());root.addView(print);
        template.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){updatePreview();}public void afterTextChanged(Editable e){}});return sc;
    }
    private void pickTable(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"text/csv","text/comma-separated-values","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});try{startActivityForResult(i,PICK_TABLE);}catch(Throwable e){Ui.toast(this,"无法打开文件选择器");}}
    private void pickCode(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");try{startActivityForResult(i,PICK_CODE);}catch(Throwable e){Ui.toast(this,"无法打开图片选择器");}}
    private void camera(){Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);try{startActivityForResult(i,CAMERA);}catch(Throwable e){Ui.toast(this,"没有可用相机应用");}}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null)return;try{if(req==PICK_TABLE&&data.getData()!=null){DataTableReader.Table t=DataTableReader.read(this,data.getData());ProductStore.save(this,t);setTable(t,"商品库已导入并保存在本机");}else{Bitmap b=null;if(req==PICK_CODE&&data.getData()!=null)b=ImageLoader.load(this,data.getData());else if(req==CAMERA&&data.getExtras()!=null&&data.getExtras().get("data") instanceof Bitmap)b=(Bitmap)data.getExtras().get("data");if(b!=null){Result r=BarcodeDecodeUtil.decode(b);query.setText(r.getText());find(r.getText());}}}catch(Throwable e){Ui.toast(this,"处理失败："+e.getMessage());}}
    private void setTable(DataTableReader.Table t,String note){table=t;matched=-1;keyColumn.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,t.headers));info.setText(note+" · "+t.rows.size()+" 条 · "+t.headers.size()+" 个字段");if(template.getText().length()==0){StringBuilder b=new StringBuilder();for(String h:t.headers){if(b.length()>0)b.append('\n');b.append(h).append("：{").append(h).append("}");}template.setText(b.toString());}updatePreview();}
    private void find(String q){if(table==null||table.rows.isEmpty()){Ui.toast(this,"请先导入商品库");return;}if(q.isEmpty()){Ui.toast(this,"请输入或扫描商品编号");return;}int key=Math.max(0,keyColumn.getSelectedItemPosition()),found=-1;for(int i=0;i<table.rows.size();i++)if(table.value(i,key).equalsIgnoreCase(q)){found=i;break;}if(found<0){String needle=q.toLowerCase(Locale.ROOT);outer:for(int i=0;i<table.rows.size();i++)for(String v:table.rows.get(i))if(v!=null&&v.toLowerCase(Locale.ROOT).contains(needle)){found=i;break outer;}}matched=found;if(found<0){match.setText("未找到："+q);updatePreview();return;}StringBuilder b=new StringBuilder("已匹配第 "+(found+1)+" 条\n");for(int j=0;j<table.headers.size();j++)b.append(table.headers.get(j)).append("：").append(table.value(found,j)).append('\n');match.setText(b.toString());updatePreview();}
    private String render(){if(table==null||matched<0)return "";String s=template.getText().toString();for(int i=0;i<table.headers.size();i++)s=s.replace("{"+table.headers.get(i)+"}",table.value(matched,i));return s;}
    private void updatePreview(){if(preview==null)return;String s=render();if(s.isEmpty()){Bitmap old=rendered;rendered=null;Bitmap op=previewBitmap;previewBitmap=null;preview.setImageDrawable(null);if(old!=null&&!old.isRecycled())old.recycle();if(op!=null&&!op.isRecycled())op.recycle();return;}try{Bitmap next=RasterEncoder.textBitmap(s,24*getResources().getDisplayMetrics().scaledDensity,false,0,5);Bitmap old=rendered;rendered=next;if(old!=null&&old!=next&&!old.isRecycled())old.recycle();RasterEncoder.Raster r=RasterEncoder.encode(next,200,RasterEncoder.Dither.THRESHOLD);r=PrinterManager.get(this).previewRaster(r);Bitmap shown=RasterEncoder.toBitmap(r,1200);Bitmap op=previewBitmap;previewBitmap=shown;preview.setImageBitmap(shown);if(op!=null&&op!=shown&&!op.isRecycled())op.recycle();Ui.pulse(preview);}catch(Throwable ignored){}}
    private void printMatched(){String s=render();if(s.isEmpty()){Ui.toast(this,"请先选择商品");return;}try{Bitmap b=rendered!=null?rendered:RasterEncoder.textBitmap(s,24*getResources().getDisplayMetrics().scaledDensity,false,0,5);RasterEncoder.Raster r=RasterEncoder.encode(b,200,RasterEncoder.Dither.THRESHOLD);final String summary=s.length()>60?s.substring(0,60)+"…":s;PrinterManager.get(this).print(this,new PrinterManager.BitmapHolder(r),(ok,msg)->{if(!"已取消打印".equals(msg))Ui.toast(this,msg);if(ok)HistoryStore.addRaster(this,"商品信息",summary,r);});if(b!=rendered&&!b.isRecycled())b.recycle();}catch(Throwable e){Ui.toast(this,"生成标签失败："+e.getMessage());}}
    @Override protected void onDestroy(){if(rendered!=null&&!rendered.isRecycled())rendered.recycle();if(previewBitmap!=null&&!previewBitmap.isRecycled())previewBitmap.recycle();rendered=null;previewBitmap=null;super.onDestroy();}
}
