package com.qring.print;

import android.app.*;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.util.*;

public class TemplateActivity extends Activity {
    private LinearLayout list,manageBar;private Button manageButton,selectAllButton,deleteButton;private boolean managing;private final HashSet<String> selected=new HashSet<>();private final ArrayList<Bitmap> previews=new ArrayList<>();
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(build());}
    @Override protected void onResume(){super.onResume();render();}
    private View build(){Ui.resolvePalette(this);LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Ui.BG);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);LinearLayout root=Ui.page(this,"我的模板");sc.addView(root);shell.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout intro=Ui.card(this);intro.addView(Ui.hint(this,"所有模板都保存在本机，可预览、打印、复制、重命名和批量管理；不依赖服务器。"));Button gallery=Ui.button(this,"浏览内置行业模板");gallery.setOnClickListener(v->startActivity(new Intent(this,BuiltInTemplateActivity.class)));intro.addView(gallery);root.addView(intro);
        LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);manageButton=Ui.button(this,"批量管理");selectAllButton=Ui.button(this,"全选");deleteButton=Ui.button(this,"删除选中");manageButton.setOnClickListener(v->{managing=!managing;if(!managing)selected.clear();render();});selectAllButton.setOnClickListener(v->{selected.clear();for(TemplateStore.Item i:TemplateStore.list(this))selected.add(i.id);render();});deleteButton.setOnClickListener(v->deleteSelected());top.addView(manageButton,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));top.addView(selectAllButton,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));top.addView(deleteButton,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));manageBar=top;root.addView(top);
        list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);shell.addView(Ui.bottomNav(this,TemplateActivity.class));return shell;}
    private void render(){if(list==null)return;recyclePreviews();list.removeAllViews();manageBar.setVisibility(View.VISIBLE);manageButton.setText(managing?"完成":"批量管理");selectAllButton.setVisibility(managing?View.VISIBLE:View.GONE);deleteButton.setVisibility(managing?View.VISIBLE:View.GONE);List<TemplateStore.Item> a=TemplateStore.list(this);if(a.isEmpty()){list.addView(Ui.emptyState(this,"T","还没有我的模板","可从标签画布、文本打印、打印历史或内置模板保存，之后会在这里显示真实缩略预览。","浏览内置模板",v->startActivity(new Intent(this,BuiltInTemplateActivity.class))));return;}
        for(TemplateStore.Item item:a){LinearLayout card=Ui.card(this);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);if(managing){CheckBox box=new CheckBox(this);box.setChecked(selected.contains(item.id));box.setOnCheckedChangeListener((v,c)->{if(c)selected.add(item.id);else selected.remove(item.id);});head.addView(box);}LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView t=new TextView(this);t.setText(item.name);t.setTextSize(17);t.setTextColor(Ui.TEXT);t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);tx.addView(t);TextView time=Ui.hint(this,HistoryStore.formatTime(item.time));time.setPadding(0,0,0,0);tx.addView(time);head.addView(tx,new LinearLayout.LayoutParams(0,-2,1));card.addView(head);
            Bitmap b=TemplateStore.loadPreview(item);if(b!=null)previews.add(b);ImageView iv=new ZoomablePreviewView(this);iv.setAdjustViewBounds(true);iv.setScaleType(ImageView.ScaleType.FIT_CENTER);iv.setBackgroundColor(0xffffffff);iv.setImageBitmap(b);card.addView(Ui.previewFrame(this,iv,"模板预览"),new LinearLayout.LayoutParams(-1,Ui.dp(this,210)));
            if(!managing){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button p=Ui.primaryButton(this,"参数 / 打印"),cp=Ui.button(this,"复制"),r=Ui.button(this,"重命名"),d=Ui.button(this,"删除");p.setOnClickListener(v->print(item));cp.setOnClickListener(v->copy(item));r.setOnClickListener(v->rename(item));d.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("删除模板“"+item.name+"”？").setPositiveButton("删除",(x,w)->{TemplateStore.delete(this,item.id);render();}).setNegativeButton("取消",null).show());row.addView(p,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));row.addView(cp,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));row.addView(r,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));row.addView(d,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));card.addView(row);}list.addView(card);}
    }
    private void deleteSelected(){if(!managing){managing=true;render();return;}if(selected.isEmpty()){Ui.toast(this,"请先选择模板");return;}new AlertDialog.Builder(this).setTitle("批量删除").setMessage("确定删除选中的 "+selected.size()+" 个模板？").setPositiveButton("删除",(d,w)->{for(String id:new ArrayList<>(selected))TemplateStore.delete(this,id);selected.clear();managing=false;render();}).setNegativeButton("取消",null).show();}
    private void copy(TemplateStore.Item i){try{TemplateStore.duplicate(this,i,i.name+" 副本");Ui.toast(this,"模板已复制");render();}catch(Throwable e){Ui.toast(this,"复制失败："+e.getMessage());}}
    private void rename(TemplateStore.Item i){EditText e=new EditText(this);e.setText(i.name);new AlertDialog.Builder(this).setTitle("重命名模板").setView(e).setPositiveButton("保存",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()){TemplateStore.rename(this,i.id,n);render();}}).setNegativeButton("取消",null).show();}
    private void print(TemplateStore.Item i){try{Bitmap b=TemplateStore.load(i);if(b==null){Ui.toast(this,"模板图片损坏");return;}RasterEncoder.Raster r=RasterEncoder.encode(b,180,RasterEncoder.Dither.THRESHOLD);if(!b.isRecycled())b.recycle();PrinterManager.get(this).print(this,new PrinterManager.BitmapHolder(r),(ok,msg)->{if(!"已取消打印".equals(msg))Ui.toast(this,msg);if(ok)HistoryStore.addRaster(this,"模板",i.name,r);});}catch(OutOfMemoryError e){Ui.toast(this,"模板过大，当前设备内存不足");}catch(Throwable e){Ui.toast(this,"模板读取失败："+e.getMessage());}}
    private void recyclePreviews(){for(Bitmap b:previews)if(b!=null&&!b.isRecycled())b.recycle();previews.clear();}
    @Override protected void onDestroy(){recyclePreviews();super.onDestroy();}
    @Override public boolean dispatchTouchEvent(MotionEvent e){if(Ui.handleTabSwipe(this,TemplateActivity.class,e))return true;return super.dispatchTouchEvent(e);}

}
