package com.qring.print;

import android.app.*;
import android.graphics.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;

public class TextPrintActivity extends Activity {
    private EditText text;private SeekBar size,lineGap,charGap,stretch,ink;private CheckBox bold,italic,underline,vertical,curved;private Spinner align,font;private ImageView preview;private Bitmap previewBitmap;private Handler handler=new Handler(Looper.getMainLooper());private Runnable pending;
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(build());String incoming=getIntent().getStringExtra("incoming_text");if(incoming!=null)text.setText(incoming);schedulePreview();}
    private View build(){
        ScrollView sc=new ScrollView(this);LinearLayout root=Ui.page(this,"文本排版");sc.addView(root);
        LinearLayout input=Ui.card(this);TextView label=Ui.hint(this,"内容 · 输入时实时刷新打印效果");input.addView(label);text=new EditText(this);text.setHint("输入要打印的文字…");text.setMinLines(5);text.setTextSize(18);text.setBackgroundColor(0x00ffffff);input.addView(text,new LinearLayout.LayoutParams(-1,Ui.dp(this,160)));root.addView(input);

        preview=new ZoomablePreviewView(this);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackgroundColor(0xffffffff);FrameLayout pf=Ui.previewFrame(this,preview,"实时纸张预览 · 384 dots");root.addView(pf,new LinearLayout.LayoutParams(-1,Ui.dp(this,300)));

        LinearLayout styleCard=Ui.card(this);styleCard.addView(Ui.hint(this,"排版样式"));
        TextView sz=Ui.hint(this,"字号 · 36sp");styleCard.addView(sz);size=new SeekBar(this);size.setMax(60);size.setProgress(24);size.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){sz.setText("字号 · "+(12+p)+"sp");schedulePreview();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});styleCard.addView(size);
        TextView iw=Ui.hint(this,"笔画粗细 · 标准");styleCard.addView(iw);ink=new SeekBar(this);ink.setMax(8);ink.setProgress(0);ink.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){iw.setText("笔画粗细 · "+(p==0?"标准":"增强 "+p));schedulePreview();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});styleCard.addView(ink);
        TextView lg=Ui.hint(this,"行间距");styleCard.addView(lg);lineGap=new SeekBar(this);lineGap.setMax(32);lineGap.setProgress(6);styleCard.addView(lineGap);
        TextView cg=Ui.hint(this,"字间距");styleCard.addView(cg);charGap=new SeekBar(this);charGap.setMax(16);charGap.setProgress(0);styleCard.addView(charGap);
        TextView st=Ui.hint(this,"水平拉伸 · 100%");styleCard.addView(st);stretch=new SeekBar(this);stretch.setMax(150);stretch.setProgress(50);stretch.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){st.setText("水平拉伸 · "+(50+p)+"%");schedulePreview();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});styleCard.addView(stretch);
        LinearLayout styles=new LinearLayout(this);styles.setOrientation(LinearLayout.HORIZONTAL);bold=new CheckBox(this);bold.setText("加粗");italic=new CheckBox(this);italic.setText("斜体");underline=new CheckBox(this);underline.setText("下划线");vertical=new CheckBox(this);vertical.setText("竖排");curved=new CheckBox(this);curved.setText("弧形");styles.addView(bold);styles.addView(italic);styles.addView(underline);styles.addView(vertical);styles.addView(curved);styleCard.addView(styles);
        font=new Spinner(this);font.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"无衬线","衬线","等宽","圆体","窄体"}));styleCard.addView(font);
        align=new Spinner(this);align.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"左对齐","居中","右对齐"}));styleCard.addView(align);root.addView(styleCard);

        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button save=Ui.button(this,"保存模板"),load=Ui.button(this,"载入上次");actions.addView(save,new LinearLayout.LayoutParams(0,Ui.dp(this,52),1));actions.addView(load,new LinearLayout.LayoutParams(0,Ui.dp(this,52),1));root.addView(actions);
        Button print=Ui.primaryButton(this,"预览确认并打印");root.addView(print);
        save.setOnClickListener(v->{Bitmap b=null;try{b=render();String s=text.getText().toString();getSharedPreferences("template",0).edit().putString("last_text",s).apply();TemplateStore.save(this,"文本模板 "+HistoryStore.formatTime(System.currentTimeMillis()),b);Ui.toast(this,"模板已保存");}catch(Throwable e){Ui.toast(this,"模板保存失败："+e.getMessage());}finally{if(b!=null&&!b.isRecycled())b.recycle();}});
        load.setOnClickListener(v->text.setText(getSharedPreferences("template",0).getString("last_text","")));print.setOnClickListener(v->doPrint());
        bindLivePreview();return sc;
    }
    private void bindLivePreview(){text.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){schedulePreview();}public void afterTextChanged(Editable e){}});SeekBar.OnSeekBarChangeListener l=new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){schedulePreview();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){schedulePreview();}};lineGap.setOnSeekBarChangeListener(l);charGap.setOnSeekBarChangeListener(l);android.widget.CompoundButton.OnCheckedChangeListener cl=(v,c)->schedulePreview();bold.setOnCheckedChangeListener(cl);italic.setOnCheckedChangeListener(cl);underline.setOnCheckedChangeListener(cl);vertical.setOnCheckedChangeListener(cl);curved.setOnCheckedChangeListener((v,c)->{if(c&&vertical.isChecked())vertical.setChecked(false);schedulePreview();});android.widget.AdapterView.OnItemSelectedListener al=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){schedulePreview();}public void onNothingSelected(android.widget.AdapterView<?> p){}};font.setOnItemSelectedListener(al);align.setOnItemSelectedListener(al);}
    private void schedulePreview(){if(pending!=null)handler.removeCallbacks(pending);pending=()->safePreview();handler.postDelayed(pending,100);}
    private String content(){String s=text.getText().toString();if(s.trim().isEmpty())s="预览文字";if(vertical.isChecked()){StringBuilder b=new StringBuilder();for(int i=0;i<s.length();i++){char c=s.charAt(i);b.append(c);if(c!='\n'&&i+1<s.length())b.append('\n');}s=b.toString();}return s;}
    private String family(){switch(font.getSelectedItemPosition()){case 1:return "serif";case 2:return "monospace";case 3:return "sans-serif-rounded";case 4:return "sans-serif-condensed";default:return "sans-serif";}}
    private Bitmap render(){int sp=12+size.getProgress();float px=sp*getResources().getDisplayMetrics().scaledDensity;if(curved.isChecked())return curvedBitmap(content(),px);float sx=(50+stretch.getProgress())/100f;return RasterEncoder.textBitmap(content(),px,bold.isChecked(),italic.isChecked(),underline.isChecked(),align.getSelectedItemPosition(),lineGap.getProgress(),charGap.getProgress(),family(),sx,ink.getProgress()*.55f);}
    private Bitmap curvedBitmap(String raw,float px){String s=raw.replace("\n"," ");if(s.length()>80)s=s.substring(0,80);Bitmap b=Bitmap.createBitmap(QringProtocol.WIDTH_DOTS,220,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(Color.WHITE);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(Color.BLACK);p.setTextSize(px);p.setTextScaleX((50+stretch.getProgress())/100f);int style=(bold.isChecked()?Typeface.BOLD:Typeface.NORMAL)|(italic.isChecked()?Typeface.ITALIC:Typeface.NORMAL);p.setTypeface(Typeface.create(family(),style));p.setUnderlineText(underline.isChecked());if(ink.getProgress()>0){p.setStyle(Paint.Style.FILL_AND_STROKE);p.setStrokeWidth(ink.getProgress()*.55f);}Path path=new Path();path.moveTo(14,155);path.quadTo(192,35,370,155);float width=p.measureText(s);float pathLen=405f;float offset=Math.max(0,(pathLen-width)/2f);c.drawTextOnPath(s,path,offset,0,p);return b;}
    private void safePreview(){Bitmap raw=null;try{raw=render();int threshold=getSharedPreferences("settings",0).getInt("threshold",212);RasterEncoder.Raster r=RasterEncoder.encode(raw,threshold,RasterEncoder.Dither.THRESHOLD);r=PrinterManager.get(this).previewRaster(r);Bitmap next=RasterEncoder.toBitmap(r,1800);Bitmap old=previewBitmap;previewBitmap=next;preview.setImageBitmap(next);if(old!=null&&old!=next&&!old.isRecycled())old.recycle();Ui.pulse(preview);}catch(OutOfMemoryError e){Ui.toast(this,"文本过长，当前设备内存不足");}catch(Throwable e){Ui.toast(this,"预览失败："+e.getMessage());}finally{if(raw!=null&&!raw.isRecycled())raw.recycle();}}
    private void doPrint(){try{final Bitmap b=render();int threshold=getSharedPreferences("settings",0).getInt("threshold",212);RasterEncoder.Raster r=RasterEncoder.encode(b,threshold,RasterEncoder.Dither.THRESHOLD);final String summary=shorten(text.getText().toString());if(!b.isRecycled())b.recycle();PrinterManager.get(this).print(this,new PrinterManager.BitmapHolder(r),(ok,msg)->{if(!"已取消打印".equals(msg))Ui.toast(this,msg);if(ok)HistoryStore.addRaster(this,"文本",summary,r);});}catch(OutOfMemoryError e){Ui.toast(this,"文本过长，当前设备内存不足");}catch(Throwable e){Ui.toast(this,"打印内容生成失败："+e.getMessage());}}
    private String shorten(String s){s=s.replace("\n"," ");return s.length()>40?s.substring(0,40)+"…":s;}
    @Override protected void onDestroy(){if(pending!=null)handler.removeCallbacks(pending);if(previewBitmap!=null&&!previewBitmap.isRecycled())previewBitmap.recycle();previewBitmap=null;super.onDestroy();}
}
